name: Generate DataSets and Deploy to GitHub Pages

on:
  repository_dispatch:
    types: [manual_drive_trigger]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate_contents:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xfonts-75dpi xfonts-base \
            libxrender1 libxext6 libfontconfig1 libx11-6 libjpeg-turbo8 libpng16-16
          # Download manually with webkit support
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox-0.12.6-1_linux-generic-amd64.tar.xz
          tar -xf wkhtmltox-0.12.6-1_linux-generic-amd64.tar.xz
          sudo mv wkhtmltox/bin/* /usr/local/bin/
          wkhtmltopdf --version
          
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script to generate DataSets
        env:
            GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE }}
            FOLDER_ID: ${{ secrets.FOLDER_ID }}
        run: python main.py

      - name: Commit and push generated DataSets to GitHub Pages
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add *.md static/* misc/update_guard_*.json
          git status
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[JOB] Update files"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
